# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20180206_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='categoty',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='page',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
